# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sdv/m1isdd/sbeutler/Bureau/DAMAKER/damaker_gui/ui/MainWindowV2.ui',
# licensing of '/home/sdv/m1isdd/sbeutler/Bureau/DAMAKER/damaker_gui/ui/MainWindowV2.ui' applies.
#
# Created: Mon Nov  7 14:50:42 2022
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 758)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/damaker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.splitter_horizontal = QtWidgets.QSplitter(MainWindow)
        self.splitter_horizontal.setStyleSheet("")
        self.splitter_horizontal.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_horizontal.setHandleWidth(7)
        self.splitter_horizontal.setObjectName("splitter_horizontal")
        self.splitter_vertical1 = QtWidgets.QSplitter(self.splitter_horizontal)
        self.splitter_vertical1.setBaseSize(QtCore.QSize(0, 900))
        self.splitter_vertical1.setStyleSheet("")
        self.splitter_vertical1.setOrientation(QtCore.Qt.Vertical)
        self.splitter_vertical1.setHandleWidth(7)
        self.splitter_vertical1.setObjectName("splitter_vertical1")
        self.dock1_1 = ContentDock(self.splitter_vertical1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock1_1.sizePolicy().hasHeightForWidth())
        self.dock1_1.setSizePolicy(sizePolicy)
        self.dock1_1.setStyleSheet("")
        self.dock1_1.setObjectName("dock1_1")
        self.splitter_vertical1_1 = QtWidgets.QSplitter(self.splitter_vertical1)
        self.splitter_vertical1_1.setBaseSize(QtCore.QSize(0, 900))
        self.splitter_vertical1_1.setStyleSheet("")
        self.splitter_vertical1_1.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_vertical1_1.setHandleWidth(7)
        self.splitter_vertical1_1.setObjectName("splitter_vertical1_1")
        self.dock1_2 = ContentDock(self.splitter_vertical1_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock1_2.sizePolicy().hasHeightForWidth())
        self.dock1_2.setSizePolicy(sizePolicy)
        self.dock1_2.setStyleSheet("")
        self.dock1_2.setObjectName("dock1_2")
        self.dock1_3 = ContentDock(self.splitter_vertical1_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock1_3.sizePolicy().hasHeightForWidth())
        self.dock1_3.setSizePolicy(sizePolicy)
        self.dock1_3.setStyleSheet("")
        self.dock1_3.setObjectName("dock1_3")
        self.splitter_vertical2 = QtWidgets.QSplitter(self.splitter_horizontal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_vertical2.sizePolicy().hasHeightForWidth())
        self.splitter_vertical2.setSizePolicy(sizePolicy)
        self.splitter_vertical2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_vertical2.setOpaqueResize(True)
        self.splitter_vertical2.setHandleWidth(7)
        self.splitter_vertical2.setObjectName("splitter_vertical2")
        self.dock2_1 = ContentDock(self.splitter_vertical2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock2_1.sizePolicy().hasHeightForWidth())
        self.dock2_1.setSizePolicy(sizePolicy)
        self.dock2_1.setStyleSheet("")
        self.dock2_1.setObjectName("dock2_1")
        self.splitter_horizontal2 = QtWidgets.QSplitter(self.splitter_vertical2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_horizontal2.sizePolicy().hasHeightForWidth())
        self.splitter_horizontal2.setSizePolicy(sizePolicy)
        self.splitter_horizontal2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_horizontal2.setOpaqueResize(True)
        self.splitter_horizontal2.setHandleWidth(7)
        self.splitter_horizontal2.setObjectName("splitter_horizontal2")
        self.dock2_2 = ContentDock(self.splitter_horizontal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock2_2.sizePolicy().hasHeightForWidth())
        self.dock2_2.setSizePolicy(sizePolicy)
        self.dock2_2.setStyleSheet("")
        self.dock2_2.setObjectName("dock2_2")
        self.dock2_3 = ContentDock(self.splitter_horizontal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock2_3.sizePolicy().hasHeightForWidth())
        self.dock2_3.setSizePolicy(sizePolicy)
        self.dock2_3.setStyleSheet("")
        self.dock2_3.setObjectName("dock2_3")
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 21))
        self.menubar.setStyleSheet("")
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
